### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by tinybit93** [quat1024/incorporeal#5]
---- Minecraft Crash Report ----
// I blame quaternary, author of Incorporeal.

Time: 2018-08-14 22:56:57 CDT
Description: Initializing game

java.lang.NoSuchFieldError: ROCK
    at quaternary.incorporeal.block.BlockCorporeaInhibitor.<init>(BlockCorporeaInhibitor.java:33)
    at quaternary.incorporeal.block.IncorporeticBlocks.registerBlocks(IncorporeticBlocks.java:71)
    at quaternary.incorporeal.Incorporeal$CommonEvents.blocks(Incorporeal.java:107)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_63_CommonEvents_blocks_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:738)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3926)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by quat1024** [comment]
Oh no this is odd. The missing field, `Material.ROCK`, is a vanilla block material.

Maybe I accidentally uploaded the wrong file to curse??

Can I get some more information:
- a full mod list
- the rest of the startup log
- botania version (this mod is *really* picky about the botania version)
- whether you used the build from curse or github

P.s. can you please post crash reports/logs on hastebin.com or similar, it makes the page really long :(

**Comment by tinybit93** [comment]
### **Crash report** 
https://hastebin.com/tomaneweho.cs

### **Mod List:**
Botania 
Baubles
Hwyla
Incorporeal
JEI

### **Info**
_Botania version_: Botania+r1.10-354
I used the build from curse, _incorporeal-1.0.0_

**Comment by angelnc1989** [comment]
I get the same [crash](https://pastebin.com/BN4Y3wwg)

**Comment by quat1024** [comment]
Try the one from Github. I think i uploaded a deobfuscated jar or something somehow. Oops.

**Comment by quat1024** [comment]
Fixed in 1.0.1, which doesn't really change anything, I just uploaded the right file this time. Approving on curse right now.

I am a *very* competent modder.
